### ISSUE TITLE
Perte des filtres lors du rafraichissement

### ISSUE THREAD

**Issue by AriiPortal** [AriiPortal/JIDBundle#1]
Les filtres sont perdus à chaque rafraichissement.

**Comment by AriiPortal** [comment]
Le statut est ajouté dans l'entête du tableau et est rafraichi automatiquement.
Ce bug a besoin d'être explicité.

**Comment by AxelANGENAULT** [comment]
Le serveur de l'utilisateur est dans une version antérieur d'Arii 1.6,
le bug n'est pas reproductible sur la versions d'aujourd'hui,
le bug est reproductible sur la VM 1.6 'vanillia'.

Ce serveur est dans une zone sans accès internet, 
comment faire pour corriger ce problème dans ce cas ?

**Comment by AriiPortal** [comment]
Il faut récupérer le zip et le décompresser dans la partie src du serveur.

**Comment by AriiPortal** [comment]
Semble déjà corrigé.
