### ISSUE TITLE
Instaurer le Role "lecteur"

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/JIDBundle#16]
Bonjour,

Serait-il possible de créer un "role" de "lecteur" pouvant s'appliquer à ce module.
L'objectif est de limiter ce type d'utilisateurs à une simple consultation sans action possible sur les traitements, les ordres, les chaines etc ?

Merci

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/38933038835939/213936784614897)

**Comment by AriiPortal** [comment]
Bonjour,

Le rôle lecteur n'existe pas, c'est le rôle user qui est utilisé par défaut. On ne supprime pas des droits à un utilisateurs mais on lui ajoute des options en fonction de son rôle. Par défaut, aucun bouton de relance de job n'est visible sauf si on a le rôle OPERATOR.
Pour plus d'information:
http://wiki.sos-paris.com/index.php/Cr%C3%A9er_un_compte_en_lecture_seule

Bonne journée, 
Eric
