### ISSUE TITLE
Reader

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/JIDBundle#21]
Bonjour,

un utilisateur en lecture seule (ROLE_USER) a accès à trois bundles : suivi, carto et plan.
Sur le suivi, il a des droits identiques à un opérateur.
Relance de jobs, d'ordre....
Il faudrait que les boutons d'actions soient neutralisés ou effacés.
jf

**Comment by jfpace** [comment]
idem sur la partie moteur, droits étendus (arret / redemmarrage).

**Comment by AriiPortal** [comment]
Bonjour,

Est ce que je peux avoir le résultat des 2 requêtes sql suivant:
- SELECT username,roles FROM `arii_user`
- SELECT * FROM `arii_parameter` WHERE name='modules'

Est ce qu'il y a une ligne "arii_modules" dans le fichier app/config/config.yml ?

Bonne journée, 
Eric

**Comment by jfpace** [comment]
Bonjour,

1) SELECT username,roles FROM arii_user
JID(ROLE_USER),DS(ROLE_USER),JOC(ROLE_USER),GVZ(ROLE_USER),Report(ROLE_USER),Admin(ROLE_ADMIN)

2) SELECT * FROM arii_parameter WHERE name='modules'
username roles (DC2Type:array)
admin      a:1:{i:0;s:10:"ROLE_ADMIN";}
operator  a:1:{i:0;s:13:"ROLE_OPERATOR";}
builder     a:1:{i:0;s:12:"ROLE_BUILDER";}
user          a:0:{}


3) Est ce qu'il y a une ligne "arii_modules" dans le fichier app/config/config.yml ?
Non.

**Comment by AriiPortal** [comment]
Bonjour,

D'après la configuration, il faut être ROLE_USER pour voir les modules et ROLE_ADMIN pour le module admin mais le user qui est défini n'a aucun rôle, il n'a donc droit à aucun module. Il faut promouvoir l'utilisateur "user" comme indiqué dans la documentation: [http://wiki.sos-paris.com/index.php/Cr%C3%A9er_un_compte_en_lecture_seule](http://wiki.sos-paris.com/index.php/Cr%C3%A9er_un_compte_en_lecture_seule)

Dans cet exemple, il faudrait:
`php app/console fos:user:promote user ROLE_USER`

Bonne journée, 
Eric
