### ISSUE TITLE
heure des logs

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/JIDBundle#23]
Bonjour,
dans le jid d'une VM fraichement installée, la vérification du log d'un job montre un décalage d'une (ou deux avec le changmeent d'heure) heures sur la première ligne uniquement du log.
Nous avons vérifié l'heure du système, ok.
Dans la bd, l'historique des résultats est à la bonne heure aussi.

jf

**Comment by AriiPortal** [comment]
Bonjour,

Un ordre qui démarre à 11:23 sera indiqué comme suit dans le log:
`2017-04-18 13:23:01.683+0200 [info]`   
Idem pour les jobs.
Est il possible d'avoir une copie d'écran pour identifier plus précisément sur quel écran se situe le problème ?

Merci, 
Eric

**Comment by jfpace** [comment]
Bonjour,
Nous avons l'heure du host, l'heure de la VM et l'heure du scheduler (php.ini).
Normalement les deux derniers sont identiques, mais on peut facilement avoir des VM en heure locale dédiées à des site distants.
Le pb se situe dans jid sur order voir copie écran) dans la partie haute l'order est à la bonne heure mais dans les onglets en bas, on est sur l'heure du host pour l'onglet ordre. et l'onglet journal on a une heure différente. Il ya visiblement accès à des sources différentes (main log, log de l'ordre et bdd). Existe-til une remise à l'heure automatique ? 
![capture d ecran 2017-04-18 a 16 16 53](https://cloud.githubusercontent.com/assets/17028741/25137877/4c555fde-2459-11e7-939b-a4cf549a7e45.png)
![capture d ecran 2017-04-18 a 16 16 30](https://cloud.githubusercontent.com/assets/17028741/25137889/514fad1e-2459-11e7-84c6-d8dcddb434cb.png)

**Comment by AriiPortal** [comment]
C'est une ancienne version du JID qui publiait les logs sous forme de tableau mais on nous avait conseillé de revenir à l'affichage plus classique du produit natif.

**Comment by jfpace** [comment]
le prochain upgrade résoudra t'il  ce pb ?
