### ISSUE TITLE
JID liste des moteurs

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/JIDBundle#24]
Bonjour,

Dans le jid/moteurs, certains moteurs apparaissent deux fois dans la liste.

jf

**Comment by AriiPortal** [comment]
Bonjour,

Le module jid est une lecture de la base de données du jobscheduler, cette liste est un select de la table scheduler_instances. Cette table est remplie par l'exécution du job CreateDaysSchedule. 
Pour vérifier cela, il suffit de faire la commande sql suivante:
`select * from scheduler_instances`
On devrait voir plusieurs fois le même moteur dans cette liste, il suffit de supprimer les doublons.
Il serait possible de supprimer ce moteur à travers Arii mais il n'est pas dans le rôle d'Arii d'écrire dans la base de données d'un produit tiers, même pour correction.
A noter que le jid de berlin et les premières versions d'arii se basait sur cette table mais, comme le souligne ce ticket, les doublons induisent un manque de fiabilité. La configuration est maintenant manuelle à travers le module admin.

Bonne journée,
Eric

**Comment by jfpace** [comment]
On devrait donc résoudre ce point en passant en V2.
Ca nous ramène sur la procédure d'install.
tu peux fermer ce ticket dans ce cas.

**Comment by AriiPortal** [comment]
La v2 ne corrigera pas les problèmes de configuration de jobscheduler, c'est à vous de corriger les corruptions de base pour qu'Arii.
Ce ticket était déjà fermé car il s'agit d'un problème JobScheduler.
Concernant la procédure d'installation, je n'ai pas vu de ticket en ce sens, il faudrait formaliser le besoin car on a autant de demande de package qu'il y a d'utilisation.
