### ISSUE TITLE
Changement de langue

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/JIDBundle#3]
Bonjour,

`http://10.0.0.19/app_dev.php/jid/fr/silent`
Je ne pense pas que la clef `You have to correct the following field:` n'est pas traduisible du fait de la ponctuation, merci d'y remédier.
(Je mets la clef sans ponctuation dans les fichiers messages.)

**Comment by AriiPortal** [comment]
Corrigé.
